behaviors:
 SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 17000000
    time_horizon: 1000
    summary_freq: 10000
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      
environment_parameters:
  is_curriculum:
    curriculum:
      - name: OnlyLesson
        value: 1.0
  opponent_speed:
    curriculum:
      - name: Lesson1 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: SoccerTwos
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.05
        value: 0.25
      - name: Lesson2 # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: SoccerTwos
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
        value: 0.5
      - name: Lesson3 # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: SoccerTwos
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.15
        value: 0.75
      - name: Lesson4 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: SoccerTwos
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.2
        value: 1.0
      - name: Lesson5 # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: SoccerTwos
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.25
        value: 1.25
      - name: Lesson6 # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: SoccerTwos
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.3
        value: 1.5
      - name: Lesson7 # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: SoccerTwos
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.35
        value: 1.75
      - name: MyLastLesson
        value: 2.0
  ball_touch_reward:
    curriculum:
      - name: Lesson1 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: SoccerTwos
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
        value: 0.3
      - name: Lesson2 # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: SoccerTwos
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.2
        value: 0.2
      - name: Lesson3 # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: SoccerTwos
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.3
        value: 0.1
      - name: MyLastLesson
        value: 0.0