behaviors:
 SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 2048
      buffer_size: 204800
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 1000
    summary_freq: 10000
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
environment_parameters:
  Learning:
    curriculum:
      - name: Lesson1 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: SoccerTwos
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
          opponent_speed: 0.0
          parameters:
            opponent_speed: 0.0
            opponent_exist: 1.0
            ball_touch_reward: 0.3
        value: 2.0
      - name: Lesson2 # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: SoccerTwos
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.2
          parameters:
            opponent_speed: 0.5
            opponent_exist: 1.0
            ball_touch_reward: 0.2
          require_reset: true
        value: 4.0
      - name: Lesson3 # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: SoccerTwos
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.2
          parameters:
            opponent_speed: 0.25
            opponent_exist: 1.0
            ball_touch_reward: 0.1
          require_reset: true
        value: 6.0
      - name: MyLastLesson
        value: 8.0